wishlist/api/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from api.views import *

# # app_name = 'user'

urlpatterns = [
    path('create_users/', create_users, name='create_user_view'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('view_users/', view_users, name='view_users_view'),
    path('view_user/<str:pk>/', view_user, name='view_user_view'),
    path('get_ID/<str:pk>/', get_id, name='get_ID_view'),
    path('update_user/<str:pk>', update_user, name='update_user_view'),
    path('delete_user/<str:pk>', delete_user, name='register_view'),
    path('view_items/', view_items, name='view_items_view'),
    path('view_item_by_id/<str:pk>', view_items_by_id, name='view_item_by_id_view'),
    path('view_userlists/', view_userlists, name='view_userlists_view'),
    path('view_userlists_by_userId/<str:pk>', view_userlist_by_userId, name='view_userlists_by_userId_view'),
    path('view_item_by_userlistID/<str:pk>', view_items_by_userlistID, name='view_item_by_userlistID_view'),
    path('view_items_by_user_id/<str:pk1>/<str:pk2>', view_items_by_user, name='view_items_by_user_id_view'),
    path('view_item_by_user_id/<str:pk1>/<str:pk2>/<str:pk3>', view_item_by_user, name='view_item_by_user_id_view'),
    path('delete_item_by_user/<str:pk1>/<str:pk2>/<str:pk3>', delete_item_by_user, name='delete_item_by_user_view'),
    path('update_item_by_user/<str:pk1>/<str:pk2>/<str:pk3>', update_item_by_user, name='update_item_by_user_view'),
    path('create_item_by_user/<str:pk1>/<str:pk2>/<str:pk3>', create_item_by_user, name='create_item_by_user_view'),
    path('create_item/', create_item, name='create_item_view'),
    path('delete_item/<str:pk>', delete_item, name='delete_item_view'),
    path('update_item/<str:pk>', update_item, name='update_item_view'),
]

wishlist/items/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from items import views as item_views
from django.shortcuts import redirect
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('items/', item_views.ListAllItems),
    path('items/<int:item_id>', item_views.ShowItem, name="specific_item"),
    path('items/item=<int:item_id>user=<int:user_id>list=<int:list_id>', item_views.AddItem, name="add_item"),
    path('userlist/', item_views.ShowUsersList, name="show_user_list")
]

wishlist/wishlist/urls.py
from django.urls.conf import re_path
from addItems import views as addItems_views
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from items import views as item_views
from django.shortcuts import redirect
from rest_framework.authtoken.views import obtain_auth_token
from users import views as user_views
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('', include(('items.urls', 'items'), namespace="items_app")),
    path('items/', item_views.ListAllItems),
    path('register/', user_views.register, name='register'),
    path('login/', user_views.login, name='login'),
    path('update/', user_views.update, name='update'),
    path('accountDetails/', user_views.account, name='accountDetails'),

    #REST API URL'S
    path('api/', include('api.urls')),
    
]

wishlist/items/models.py
# from django.db import models
# from django.db.models.deletion import CASCADE
# from django.contrib.auth.models import User
# # from home.models import List

# # if tables need to be updated, change the model,then run python manage.py migrate

# class Item(models.Model):
#     name = models.CharField(max_length=100)
#     price = models.FloatField(default='None')
#     image = models.URLField(default='None')
#     category = models.CharField(max_length=100, default='None')
#     description = models.TextField(default='None')

#     def __str__(self):
#         return self.name

# # List is a list of lists (userList, itemList)
# class itemList(models.Model):
#     list_name = models.CharField(max_length=100, default='New List')
#     user = models.ForeignKey(User, on_delete = models.CASCADE, blank = True, null = True)
#     user_list = models.ManyToManyField(Item)

wishlist/items/views.py
from django.shortcuts import render, redirect
from django.http import response, JsonResponse
from django.shortcuts import render
from django.shortcuts import redirect
from api.models import User, UserList
from django.contrib import messages
from api import views as api

def ListAllItems(request):
    if 'user_id' not in request.session:        
        return redirect ("/login")

    response = api.view_items(request)
    context = {'items' : response.data}

    return render(request, 'items/items.html', context)

def ShowItem(request, item_id):
    user_id = request.session['user_id']
    user_list_resp = api.view_userlist_by_userId(request, user_id)

    userlist_id = user_list_resp.data['id']
    response = api.view_items_by_id(request, item_id)

    context = {'item' : response.data, 'user' : user_id, 'list' : userlist_id}
    return render(request, 'items/item.html', context)

def AddItem(request, item_id, user_id, list_id):
    print("Item:", item_id)
    print("User:", user_id)
    print("List:", list_id)

    response = api.create_item_by_user(request, user_id, list_id, item_id)

    if response.status_code == 200:
        messages.success(request, 'Item Added!')
    else:
        messages.error(request, 'Error: Item can not be added to list.')

    return redirect("/items/{}".format(item_id))
    
def ShowUsersList(request):
    if 'user_id' not in request.session:
        return redirect ("/login")
    user_id = request.session['user_id']
    user = User.objects.get(id=user_id)
    userlist = UserList.objects.get(user=user)

    response = api.view_items_by_user(request, user_id, userlist.id)
    context = {'userlist':response.data}

    return render(request, 'items/userLists.html', context)


# def ShowUsersList(request, user_id, userlist_id):

#     response = api.view_items_by_user(request, user_id, userlist_id)
#     context = {'userlist':response.data}

#     return render(request, 'items/userLists.html', context)

wishlist/items/templates/items/item.html
{% extends "home/base.html" %}
{% block content %}
    <style>
        .btn-success:hover, .btn-success:focus, .btn-success:active, .btn-success.active, .open>.dropdown-toggle.btn-success {
            color: rgb(255, 255, 255);
            background-color: #34a13a;
            border-color: #1d65a3;
        }

        img{
            width: 70%;
            height: 70%
        }
    </style>
    <div class="row">
        <div class="col-md-6">
            {% if messages %}
                <div>
                    <h1>{{ message }}</h1>   
                </div>
                <br>
            {% endif %}

            <img src={{ item.image }}>

            <div class="row">
                <h1> {{ item.name }} </h1>
                <h2> ${{ item.price }} </h2>

                <div class="col-md-6">
                    <form action="{% url 'items_app:add_item' item.id user list %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-success btn-lg" type="submit">Add to list</button>
                    </form>
                </div>
            </div>
        </div>


        <div class="col-md-6">
            <h3>Category: {{ item.category }} </h3>
            <h4>Description: {{ item.description }}</h4>
        </div>
    </div>

{% endblock content %}

wishlist/items/templates/items/items.html
{% extends "home/base.html" %}
{% block content %}
    <style>
        #center {
            margin: auto;
            text-align: center;
            padding: 10px;
        }

        img {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        .btn-light:hover, .btn-light:focus, .btn-light:active, .btn-light.active, .open>.dropdown-toggle.btn-light {
            color: rgb(0, 0, 0);
            background-color: #87d8eb;
            border-color: #1d65a3;
        }
    </style>
    <div id="center">

        <h1> Items </h1>

        <div class="row">
        {% for item in items %}
        <div class="col-md-3">
            <form action="{% url 'items_app:specific_item' item.id %}" method="GET">
            {% csrf_token %}
                    <button class="btn btn-light" type="submit">
                        <article class="media content-section">
                            <img src={{ item.image }} height="100">
                            <div class="media-body">
                                {{ item.name }}  {{ item.price }}
                            </div>
                        </article>
                    </button>
            </form>
        </div>
        {% endfor %}
        </div>
    </div>
{% endblock content %}

wishlist/items/templates/items/userLists.html
{% extends "home/base.html" %}
{% block content %}
<!--Section: Block Content-->
<!DOCTYPE html>
<html>

<body>
    <section>

        <!--Section: Block Content-->
        <!-- <h1>{{ userlist.id }}</h1>
        <h1>{{ userlist.list_name }}</h1>
        <h1>{{ userlist.user }}</h1>
        {% for items in userlist.user_list %}
            <h2>{{ items.id }}</h2>
            <h2>{{ items.name }}</h2>
            <h2> {{ items.price }}</h2>
        {% endfor %} -->

        <!--Grid row-->

        <div class="row">

            <!--Grid column-->
            <div class="col-lg-8">

                <!-- Card -->
                <div class="mb-3">
                    <div class="pt-4 wish-list">

                        <h3 class="mb-4">Wishlist: {{userlist.list_name}}</h3>

                        {% for items in userlist.user_list %}
                        <div class="row mb-4">
                            <div class="col-md-5 col-lg-3 col-xl-3">
                                <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                                    <img class="img-thumbnail" src={{items.image}} alt="Image">
                                </div>
                            </div>
                            <div class="col-md-7 col-lg-9 col-xl-9">
                                <div>
                                    <div class="d-flex justify-content-between">
                                        <div>
                                            <h4 class="text-uppercase">{{items.name}}</h4>
                                            <p class="mb-3 text-success">ID: {{items.id}}</p>
                                            <p class="mb-3 text-success">Category: {{items.category}}</p>
                                            <p class="mb-2 text-success">Description: {{items.description}}</p>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div>
                                            <a onclick="deleteItem(`{{items.id}}`)" class="btn btn-danger" type="button"
                                                class="card-link-secondary small text-uppercase mr-3" class="delete"><i
                                                    class="fas fa-trash-alt mr-1"></i> Remove item </a>
                                            <!-- {% csrf_token %} -->
                                            <!-- onclick="updateItem({{items.id}})" -->

                                            <button class="btn btn-primary" role="button"
                                                class="card-link-secondary small text-uppercase" data-bs-toggle="modal"
                                                data-bs-target="#exampleModal"><i class="fas fa-heart mr-1"> </i> Edit
                                                item </button>

                                            <div class="modal fade" id="exampleModal" tabindex="-1"
                                                aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLabel">Update Item:
                                                                {{items.name}}
                                                            </h5>
                                                            <button type="button" class="btn-close"
                                                                data-bs-dismiss="modal" aria-label="Close"></button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <form id="form">
                                                                {% csrf_token %}
                                                                <div class="mb-3">
                                                                    <label for="formGroupExampleInput"
                                                                        class="form-label">Name</label>
                                                                    <input type="text" class="form-control"
                                                                        id="UpdateName" placeholder="IPHONE">
                                                                </div>
                                                                <div class="mb-3">
                                                                    <label for="formGroupExampleInput2"
                                                                        class="form-label">Category</label>
                                                                    <input type="text" class="form-control"
                                                                        id="UpdateCategory" placeholder="Electronics">
                                                                </div>
                                                                <div class="mb-3">
                                                                    <label for="formGroupExampleInput2"
                                                                        class="form-label">Description</label>
                                                                    <input type="text" class="form-control"
                                                                        id="UpdateDescription"
                                                                        placeholder="This is an IPHONE">
                                                                </div>
                                                            </form>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary"
                                                                data-bs-dismiss="modal">Close</button>
                                                            <button onclick="updateItem(`{{items.id}}`)" type="button"
                                                                class="btn btn-primary">Save
                                                                changes</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span><strong id="price">${{items.price}}</strong></span></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <hr class="mb-4">
                    </div>
                </div>

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4">
            </div>
            <!--Grid column-->

        </div>
        <!-- Grid row -->
        <script type="text/javascript">
            function deleteItem(id) {
                var r = confirm("Delete Item?");
                if (r == true) {
                    var apiUrl = 'https://nicnak.herokuapp.com/api/delete_item_by_user/{{userlist.user}}/{{userlist.id}}/' + id
                    fetch(apiUrl).then(response => {
                        return response.json();
                    }).then(data => {
                        console.log(data);
                        window.location.reload();
                    }).catch(err => {
                        console.log(data);
                    })
                }
                else {
                    console.log("You pressed Cancel!");
                }
            }

            function updateItem(id) {
                var form = document.getElementById('form')
                csrftoken = form.getElementsByTagName("input")[0].value
                console.log('Newtoken: ', form.getElementsByTagName("input")[0].value)
                var name = document.getElementById("UpdateName").value
                var category = document.getElementById("UpdateCategory").value
                var description = document.getElementById("UpdateDescription").value

                const dataObject = {
                    name: name,
                    category: category,
                    description: description
                };

                var apiUrl = 'https://nicnak.herokuapp.com/api/update_item_by_user/{{userlist.user}}/{{userlist.id}}/' + id
                fetch(apiUrl, {
                    method: 'PUT',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrftoken,
                    },
                    body: JSON.stringify(dataObject)
                }).then(response => {
                    return response.json()
                }).then(data => {
                    console.log(data)
                    window.location.reload();
                });
                // this is the data we get after putting our data,
            }
        </script>
    </section>
</body>

</html>
{% endblock content %}